### PR TITLE
Fix BLE in SearchEngine and add test

### LINKED ISSUE #427: BadLocationException thrown in SearchEngine if searchWrap = true and searchForward = false in empty document
**Description**
As the title implies:
```
javax.swing.text.BadLocationException: Length must be positive
	at java.desktop/javax.swing.text.AbstractDocument.getText(AbstractDocument.java:777)
	at java.desktop/javax.swing.text.JTextComponent.getText(JTextComponent.java:1368)
	at org.fife.ui.rtextarea.SearchEngine.getFindInText(SearchEngine.java:261)
	at org.fife.ui.rtextarea.SearchEngine.find(SearchEngine.java:124)
	at org.fife.ui.rsyntaxtextarea.demo.FindAndReplaceDemo.actionPerformed(FindAndReplaceDemo.java:113)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Steps to Reproduce**
Specific steps to reproduce the behavior:
1. Modify `org.fife.ui.rsyntaxtextarea.demo.FindAndReplaceDemo` so that the created SearchContext has the wrap flag set.
2. Empty the main editing pane.
3. Type some search query, select 'Find Previous'

**Expected behavior**
Search wrapping should be allowed but probably ignored on empty documents

**Actual behavior**
BLE above is thrown.

### PR DESCRIPTION
**Pull request by paul-griffith**
Fixes #427 

Catching and rethrowing the BLE is pretty hokey... but to be fair, catching it and dumping the stack trace wasn't much better 😉

### CODE REVIEW

File: RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/SearchEngine.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ public static SearchResult find(JTextArea textArea, SearchContext context) {
 		boolean doMarkAll = textArea instanceof RTextArea && context.getMarkAll();
 
 		String text = context.getSearchFor();
-		if (text==null || text.length()==0) {
+		if (text==null || text.length()==0 || textArea.getText().isEmpty()) {
```
Comment (bobbylight) [inline RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/SearchEngine.java:75]: This empty-check is expensive for large documents, can you update this to be:

```suggestion
if (text == null || text.isEmpty() || textArea.getDocument().getLength() == 0) {
```

File: RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/SearchEngine.java [hunk 2]
```diff
@@ -262,7 +262,7 @@ private static String getFindInText(JTextArea textArea, int start,
 			}
 		} catch (BadLocationException ble) {
 			// Never happens; findIn will be null anyway.
-			ble.printStackTrace();
+			throw new RuntimeException(ble);
```
Comment (bobbylight) [inline RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/SearchEngine.java:265]: I'm worried this will screw up the EDT, if an uncaught exception is thrown.  At least that's my recollection.  That's why I'm currently just doing a `printStackTrace()` (which I agree with you is pretty hokey).  Is that a concern?

**Review by bobbylight — CHANGES_REQUESTED** [review]
One question and one suggestion!

File: RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/SearchEngine.java (hunk 2 above)
Comment (paul-griffith) [reply RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/SearchEngine.java:265]: Hm, I think you're right about the EDT... but if it's not re-thrown, it can't actually be caught in a test. I guess that's probably the lesser of two evils here though.

Comment (bobbylight) [reply RSyntaxTextArea/src/main/java/org/fife/ui/rtextarea/SearchEngine.java]: Yeah, I'm not necessaarily happy with it but like the comment says - it's not supposed to happen :). Fortunately you caught a bug where it *does*!

RSTA follows this pattern of calling `Throwable.printStackTrace()` everywhere that e.b. `BadLocationException` is thrown by Swing API's but shouldn't happen "in real life" due to using offsets fetched from the Document, etc.  I was reluctant to rethrow checked exceptions like `BadLocationException` everywhere, since that adds complexity for client apps, and also didn't want to add a logging dependency to keep RSTA lightweight.  I'm happy folks are looking at other ways to approach this kind of thing though.

In any case, thanks for the PR!

**Comment by bobbylight** [comment]
@paul-griffith Yes, the Java 17 build currently fails; we have one test that uses Mockito and it looks like something changed starting in Java 15, where the mock's behavior is different and no longer works properly.  It's not related to your change, or RSTA at all.  I've opened [this Mockito ticket](https://github.com/mockito/mockito/issues/2573) to track it.  If it can't be addressed easily I'll try to look at a different way to verify stuff in that test to avoid the problem.
